name: 'qas'
data_dir: '../../qas/'
kb_path: '../../qas/foodkg.json'
train_data: 'train_vec.json'
valid_data: 'valid_vec.json'
test_data: 'test_vec.json'
test_raw_data: 'test_qas.json'
pre_word2vec: '../../qas/glove_pretrained_300d_w2v.npy'

# Full vocab
vocab_size: 8324 # please modify this, it should match the size of vocab2id
num_ent_types: 7 # please modify this, it should match the size of entityType2id
num_relations: 46 # please modify this, it should match the size of relation2id



num_query_words: 10

# Output
model_file: '../../qas/bow.model'


# Model
query_size: 64
ans_type_bow_size: 6
ans_path_bow_size: 6
ans_path_size: 2
ans_ctx_entity_bow_size: 10

vocab_embed_size: 300
hidden_size: 128
o_embed_size: 128
mem_size: 96
word_emb_dropout: 0.3
que_enc_dropout: 0.3
ans_enc_dropout: 0.2
attention: 'add'
num_hops: 1

# Training
learning_rate: 0.001
batch_size: 32
num_epochs: 100
valid_patience: 10
margin: 1

# Testing
test_batch_size: 1
test_margin:
        - 0.4

# Device
no_cuda: False
gpu: 0
